services:
  OpenWebUI:
    image: ghcr.io/open-webui/open-webui:v0.5.14
    container_name: OpenWebUI
    volumes:
      - ./data:/app/backend/data
    ports:
      - 2021:8080
    environment:
      - 'OLLAMA_BASE_URL=http://192.168.2.202:11434'
      - 'WEBUI_SECRET_KEY=jjnvidia4090'
      - 'ENABLE_OPENAI_API=False'
      - 'ENABLE_COMMUNITY_SHARING=False'
      - 'RAG_EMBEDDING_ENGINE=openai'
      - 'ENABLE_REALTIME_CHAT_SAVE=False'
    restart: unless-stopped
